package org.pyf.developer.bean.one.model.auth;

// Generated 2009-5-14 15:29:56 by Hibernate Tools 3.2.4.GA

import org.springframework.context.annotation.Lazy;

import javax.persistence.*;
import java.util.Date;

/**
 * SystemUrlResource generated by hbm2java
 */

@Entity
@Table(name ="TBL_CP_URLRESOURCE", schema = "cp2015db")
@Lazy(value=true)
public class SystemUrlResource implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1037074716736942607L;

	

	@Id
	@Column(name="URRE_ID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	
	@Column(name="URRE_DATE")
	private Date lastupdate;
	@Column(name="URRE_URL_PATTERN")
	private String urlPattern;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="URRE_AUTH_ID_FK",nullable=false)
	private SystemAuthority authority;

	public SystemUrlResource() {
	}

	public SystemUrlResource(SystemAuthority authority, String urlPattern,
			Date lastupdate) {
		this.authority = authority;
		this.urlPattern = urlPattern;
		this.lastupdate = lastupdate;
	}

	public SystemAuthority getAuthority() {
		return authority;
	}

	public Long getId() {
		return id;
	}

	public Date getLastupdate() {
		return lastupdate;
	}

	public String getUrlPattern() {
		return urlPattern;
	}

	public void setAuthority(SystemAuthority authority) {
		this.authority = authority;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public void setUrlPattern(String urlPattern) {
		this.urlPattern = urlPattern;
	}

	@Override
    public String toString(){
		return this.urlPattern;
	}
}
